name: iruka

on:
  pull_request:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: call checkout
        uses: actions/checkout@v3
        
      - name: Setup python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lkml
          pip install pytest

      - name: Get changed files
        id: file_changes
        uses: trilom/file-changes-action@v1.2.3

      - name: Set changed files
        id: changed_files
        run:  echo "::set-output name=CHANGED_FILES::${{steps.file_changes.outputs.files_modified }}"

      - name: execute tests script
        run: pytest -v --tb=short ./tests/test_files.py
        env:
          CHANGED_FILES: ${{ steps.changed_files.outputs.CHANGED_FILES }}
